import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import {getServerSession} from 'next-auth' 
import SessionProvider from './components/SessionProvider'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({   //async
  children, 
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(); //its a promise, so we need async
  return (
    <html lang="en" className='dark'>
      <body className={inter.className}>
      <Providers>
        <SessionProvider session={session}>
    
          {children}
     
        </SessionProvider>
           </Providers>
      </body>
    </html>
  )
}
